### ISSUE TITLE
Bug: Limit the length of war/sprint characters

### ISSUE THREAD

**Issue by wcmckee** [lisushka/Winnie_Bot#30]
**Describe the bug**
There is currently no limit on the character length for wars/sprints. Discord seems to have a limit of 2000 characters, but this is still is to long. 

**Command Syntax Used**
def createsprint(warsprint, lenth, timestart, namesprint):
    Hook(hook_url=webhook, username="Pinny",
     avatar_url='https://pbs.twimg.com/profile_images/649004216690675712/UAcrP6ol_400x400.png',
     content="!{} {} {} {}".format(warsprint, lenth, timestart, namesprint)).execute()

longname = 'w' * 1900
createsprint('war', 20, 5, longname)

**Comment by lisushka** [comment]
This fix will take the form of limiting challenge names to 150 characters.

**Comment by lisushka** [comment]
Resolved with pull request #39.
