### ISSUE TITLE
Feature Request: A quick daily reminder of the wordcount goal for the day

### ISSUE THREAD

**Issue by psh** [lisushka/Winnie_Bot#32]
Our ML posted a quick "this is day XX and your wordcount goal is YY." message to our _announcements_ channel which I found really useful.  It saved me having to go load my trusty Excel spreadsheet and check what the "day 6" wordcount was meant to be.

Ideally these posts would remain separate from the main flow of word wars and other messages, hopefully configurable as to where they get posted.

**Comment by lisushka** [comment]
Resolved with pull request #62.
