### ISSUE TITLE
Feature Request: Correct example commands

### ISSUE THREAD

**Issue by wcmckee** [lisushka/Winnie_Bot#34]
**Is your feature request related to a problem? Please describe.**
Winnie reply with correct example command when user inputs incorrect command.

**Describe the solution you'd like**
extend the error messages. Make them short and direct with giving an example of what command the user meant. Performing natural language progress in order to return the best example. Ability to react to response in order to trigger it. 

!set 34re

Winnie_Bot: Error: Your goal must be a whole number. Example command: [servers!character]set 3400

**Describe alternatives you've considered**

**Additional context**
Might be cool if winnie was reading this text from an api rather than hardcode. could make translation an option.

**Comment by wcmckee** [comment]
https://github.com/wcmckee/Winnie_Bot/tree/examplegoal

**Comment by lisushka** [comment]
Resolved with pull request #48.
