### ISSUE TITLE
Feature Request: clearer formatting/more info of debug.log 

### ISSUE THREAD

**Issue by wcmckee** [lisushka/Winnie_Bot#35]
**Is your feature request related to a problem? Please describe.**
The debug.log could be more friendly to parse and it could contain more data.

**Describe the solution you'd like**

Currently the debug.log format is: 

{"level":"info","message":"<@1> entered command !waz 20 1 hey","timestamp":"2018-11-15T02:43:59.854Z"}

I would like to switch the format to something like: 

{"level":"info", "user" : "<@1>", "message" : "!waz 20 1 hey","timestamp":"2018-11-15T02:43:59.854Z", "success" : False}

{"level":"info", "user" : "<@2>", "message" : "!war 20 1 hey","timestamp":"2018-11-16T02:43:59.854Z", "success" : True, "response": "Your war, hey (ID 3), starts in 1 minute."}

**Describe alternatives you've considered**
I could solve this somewhat by creating a script that opens the debug.log file and use re to convert to perfected format.  

**Additional context**
This would make it easier to test the commands that user inputs. The debug could also contain the response that Winnie gives. Could also contain if the command was successful or not.

**Comment by lisushka** [comment]
Resolved with pull request #58.
